package deploy

// templateData is what the generated files are rendered from.
type templateData struct {
	Domain          string
	Email           string
	LilyAddr        string
	Image           string
	BaseImage       string
	Staging         bool
	MaxSessions     int
	AuthMaxFailures int
}

func newTemplateData(opts Options, baseImage string) templateData {
	return templateData{
		Domain:          opts.Domain,
		Email:           opts.Email,
		LilyAddr:        opts.LilyAddr,
		Image:           opts.Image,
		BaseImage:       baseImage,
		Staging:         opts.Staging,
		MaxSessions:     opts.MaxSessions,
		AuthMaxFailures: opts.AuthMaxFailures,
	}
}

const dockerfileTmpl = `# Generated by zlily deploy.
#
# The binary is copied in rather than built here: it is the very zlily that
# generated this directory, so what runs in the container is what was tested.
# The base image carries a libc only when the binary needs one.
FROM {{.BaseImage}}

COPY zlily /usr/local/bin/zlily

EXPOSE 7888

ENTRYPOINT ["/usr/local/bin/zlily"]
`

const composeTmpl = `# Generated by zlily deploy.
#
# Two services: zlily serving the browser client on an internal port, and
# Traefik terminating TLS in front of it with a Let's Encrypt certificate.
# Only Traefik publishes ports; zlily is reachable only on the compose network.

services:
  zlily:
    build: .
    image: {{.Image}}
    command:
      - server
      - --listen=:7888
      - --lily={{.LilyAddr}}
      - --web
      # Rate limiting keys on the client address, which past Traefik is only
      # available from X-Forwarded-For. Safe to trust here because nothing
      # reaches this container except through Traefik.
      - --behind-proxy
{{- if .MaxSessions}}
      - --max-sessions={{.MaxSessions}}
{{- end}}
{{- if .AuthMaxFailures}}
      - --auth-max-failures={{.AuthMaxFailures}}
{{- end}}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zlily.rule=Host(` + "`" + `{{.Domain}}` + "`" + `)"
      - "traefik.http.routers.zlily.tls=true"
      - "traefik.http.routers.zlily.tls.certResolver=default"
      # Stated explicitly so Traefik never has to guess which port to use.
      - "traefik.http.services.zlily.loadbalancer.server.port=7888"
    restart: always

  reverse-proxy:
    image: traefik
    command:
      - --providers.docker
      # Without this, Traefik routes every container on the host, not just the
      # ones that asked for it.
      - --providers.docker.exposedByDefault=false
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesResolvers.default.acme.email={{.Email}}
      - --certificatesResolvers.default.acme.storage=/letsencrypt/acme.json
      - --certificatesResolvers.default.acme.httpChallenge.entryPoint=web
{{- if .Staging}}
      # Staging CA: untrusted by browsers, but its rate limits are generous.
      - --certificatesResolvers.default.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
{{- end}}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Read-only: the Docker socket is root on the host, and Traefik only ever
      # needs to read container labels.
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Issued certificates live here rather than inside the container, so
      # recreating it does not re-request them and run into the
      # duplicate-certificate rate limit.
      - ./letsencrypt:/letsencrypt
    restart: always
`

const readmeTmpl = `# zlily deployment

Generated by ` + "`zlily deploy`" + `. Serves the browser TUI at
https://{{.Domain}}/term/ with TLS from Let's Encrypt.

    docker compose up -d --build     # start (or apply changes)
    docker compose logs -f zlily     # follow the proxy log
    docker compose down              # stop

## What is here

| File | |
|---|---|
| ` + "`zlily`" + ` | The binary, copied from the one that generated this directory. |
| ` + "`Dockerfile`" + ` | Wraps that binary in ` + "`{{.BaseImage}}`" + `. |
| ` + "`docker-compose.yml`" + ` | The zlily service and Traefik in front of it. |
| ` + "`letsencrypt/acme.json`" + ` | Issued certificates. Mode 0600, and worth backing up. |

## Before this works

DNS for **{{.Domain}}** must resolve to this host, and ports 80 and 443 must
reach it. The HTTP challenge needs port 80 specifically — it is not only there
for the redirect to HTTPS.

## Updating

Rebuild zlily, then re-run ` + "`zlily deploy`" + ` with the same arguments. It
restages the binary and restarts the container; ` + "`acme.json`" + ` is left
alone, so no new certificate is requested.

## Exposure

This deployment talks to exactly one Lily server, **{{.LilyAddr}}**, fixed in
` + "`docker-compose.yml`" + `. No client can point it anywhere else.

Anyone who reaches the URL can still attempt a Lily login, so failed attempts
are rate limited per client address and concurrent sessions are capped
(` + "`--max-sessions`" + `). Both are visible in the ` + "`command:`" + ` block.
If this should not be a login form open to the whole internet, put Traefik
basic auth in front of it, or restrict it at the firewall.
`
